# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -e .
    - name: Calculate coverage
      run: |
        coverage run --source=fompy tests.py
        echo "COVERAGE=$(coverage report | grep -oP 'TOTAL\s+\d+\s+\d+\s+\K(\d+%)')" >> $GITHUB_ENV
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 9e5ba719e43ce7d459b38bb7e5c7c588
        filename: fompy-coverage.json
        label: coverage
        message: ${{ env.COVERAGE }}
        color: green

